SET CURRENT_SCHEMA = SIDEV;

SELECT * FROM CUSTOMER_ACCOUNT;


SELECT CUS_ACC_NO,CONTRACT_NO, EXT_ACC_TYPE, CURRENCY_TYPE FROM CUSTOMER_ACCOUNT WHERE CUS_ACC_ID = 14108382;                   -- CUS_ID = 706443251;