SET CURRENT_SCHEMA = SIP;

SELECT * from APP_USER;

SELECT LOGIN,USER_NAME,USER_NAME_SC, USE_ID FROM APP_USER;
SELECT USER_NAME_SC, USE_ID FROM APP_USER;

SELECT USER_NAME, USE_ID FROM APP_USER;

SELECT * FROM APP_USER
WHERE RTRIM(USER_NAME_SC) LIKE '%FHQLVFHOAD';   - to je to što bi trebalo ubaciti u kod


