package hr.vestigo.modules.collateral.jcics.co15;

import java.sql.Timestamp;
import hr.vestigo.framework.common.TableData;
import java.sql.Date;
import java.math.BigDecimal;
import java.util.Map;
import java.util.HashMap;
import hr.vestigo.framework.remote.transaction.*;

public class DeclCO15 implements MappingDecl, Decl {
	public static String cvsident = "@(#) $Header: /var/cvsroot/java/src/hr/vestigo/modules/collateral/jcics/co15/DeclCO15.java,v 1.31 2015/01/20 12:32:28 hrazst Exp $";
	private Map response = new HashMap();

	public DeclCO15() {
	}

	// in args
	public java.lang.Integer ActionListLevel = null;
	public String ScreenEntryParam = null;
	public BigDecimal use_id = null;
	public BigDecimal org_uni_id = null;

	// out args
	public TableData tblColWorkList = new TableData();

	// inner classes
	public COLLBOEINSERTMAPPING collboeinsertmapping = null;
	public COLLBOEDETAILMAPPING collboedetailmapping = null;
	public COLLBOEUPDATEMAPPING collboeupdatemapping = null;
	public COLLBOEQBEMAPP collboeqbemapp = null;

	public void setRequest(Map request) {
		ActionListLevel = (java.lang.Integer) request.get("ActionListLevel");
		ScreenEntryParam = (String) request.get("ScreenEntryParam");
		use_id = (BigDecimal) request.get("use_id");
		org_uni_id = (BigDecimal) request.get("org_uni_id");
	}

	public Map getResponse() {
		response.put("tblColWorkList", tblColWorkList);

		return response;
	}

	public Map getRefToResponseMap() {
		return response;
	}

	// Implementation of abstract superclass methods
	public MappingDecl createDecl(String mapping, Map request) throws Exception {
		if(mapping.equals("CollBoeInsertMapping")) {
			collboeinsertmapping = new COLLBOEINSERTMAPPING(request);
			return collboeinsertmapping;
		} else if(mapping.equals("CollBoeDetailMapping")) {
			collboedetailmapping = new COLLBOEDETAILMAPPING(request);
			return collboedetailmapping;
		} else if(mapping.equals("CollBoeUpdateMapping")) {
			collboeupdatemapping = new COLLBOEUPDATEMAPPING(request);
			return collboeupdatemapping;
		} else if(mapping.equals("CollBoeQbeMapp")) {
			collboeqbemapp = new COLLBOEQBEMAPP(request);
			return collboeqbemapp;
		} else {
			setRequest(request);
			return this;
		}
	}

	// INNER CLASSES
	public class COLLBOEINSERTMAPPING implements MappingDecl {
		public Map response = new HashMap();

		// in args
		public String CollBoeDialog_txtColDesc = null;
		public BigDecimal CollBoeDialog_COL_TYPE_ID = null;
		public String CollBoeDialog_txtCollTypeCode = null;
		public String CollBoeDialog_txtCollTypeName = null;
		public BigDecimal CollBoeDialog_CUS_ID = null;
		public String CollBoeDialog_txtRegNoB = null;
		public String CollBoeDialog_txtCodeB = null;
		public String CollBoeDialog_txtNameB = null;
		public BigDecimal CollBoeDialog_BOE_TYPE_ID = null;
		public String CollBoeDialog_txtBoeTypeUCV = null;
		public String CollBoeDialog_txtBoeTypeUCD = null;
		public BigDecimal CollBoeDialog_ISU_PLACE_ID = null;
		public String CollBoeDialog_txtIsuPlaCode = null;
		public String CollBoeDialog_txtIssuePlace = null;
		public Date CollBoeDialog_txtIssueDate = null;
		public BigDecimal CollBoeDialog_txtAmount = null;
		public BigDecimal CollBoeDialog_CUR_ID = null;
		public String CollBoeDialog_txtCurIdCodeChar = null;
		public BigDecimal CollBoeDialog_P_CUS_ID = null;
		public String CollBoeDialog_txtRegNoP = null;
		public String CollBoeDialog_txtCodeP = null;
		public String CollBoeDialog_txtNamePayee = null;
		public String CollBoeDialog_txtPayeeAccno = null;
		public String CollBoeDialog_txtAddData = null;
		public String CollBoeDialog_txtAddData1 = null;
		public BigDecimal CollBoeDialog_TR_CUS_ID = null;
		public String CollBoeDialog_txtRegNoTR = null;
		public String CollBoeDialog_txtCodeTR = null;
		public String CollBoeDialog_txtNameTR = null;
		public String CollBoeDialog_txtFNameTR = null;
		public String CollBoeDialog_txtSNameTR = null;
		public BigDecimal CollBoeDialog_PAY_PLACE_ID = null;
		public String CollBoeDialog_txtPayPlaceCode = null;
		public String CollBoeDialog_txtPayPlace = null;
		public String CollBoeDialog_txtPayment = null;
		public BigDecimal CollBoeDialog_COLL_CUS_ID = null;
		public String CollBoeDialog_txtRegNoT = null;
		public String CollBoeDialog_txtCodeT = null;
		public String CollBoeDialog_txtNameT = null;
		public String CollBoeDialog_txtFName = null;
		public String CollBoeDialog_txtSName = null;
		public String CollBoeDialog_txtNumberClause = null;
		public Integer CollBoeDialog_txtNumberBoe = null;
		public String CollBoeDialog_txtMaturityClause = null;
		public Date CollBoeDialog_txtMaturityDate = null;
		public String CollBoeDialog_txtPaymentClause = null;
		public String CollBoeDialog_txtProtestClause = null;
		public String CollBoeDialog_txtFeeClause = null;
		public String CollBoeDialog_txtReportClause = null;
		public String CollBoeDialog_txtIndosaClause = null;
		public String CollBoeDialog_txtCureClause = null;
		public Date CollBoeDialog_txtDATE_FROM = null;
		public Date CollBoeDialog_txtDATE_UNTIL = null;
		public String CollBoeDialog_Status = null;
		public String CollBoeDialog_StatusDesc = null;
		public String CollBoeDialog_SpecStatus = null;
		public String CollBoeDialog_SpecStatusDesc = null;
		public BigDecimal CollBoeDialog_USE_OPEN_ID = null;
		public BigDecimal CollBoeDialog_USE_ID = null;
		public BigDecimal CollBoeDialog_LA_ACC_ID = null;
		public String CollBoeDialog_txtAccNoLoan = null;
		public BigDecimal CollBoeDialog_PAYEE_ADD_ID = null;
		public String CollBoeDialog_txtPayeeFname = null;
		public String CollBoeDialog_txtPayeeSname = null;
		public BigDecimal CollBoeDialog_ORIGIN_ORG_UNI_ID = null;
		public BigDecimal CollBoeDialog_ORG_UNI_ID = null;
		public BigDecimal CollBoeDialog_USE_ID_VER_SND = null;
		public Timestamp CollBoeDialog_VER_SEND_TS = null;
		public BigDecimal CollBoeDialog_USE_ID_VER = null;
		public Timestamp CollBoeDialog_VERIFICATION_TS = null;
		public BigDecimal CollBoeDialog_USE_ID_AUT = null;
		public Timestamp CollBoeDialog_AUTORIZATION_TS = null;
		public String CollBoeDialog_BasicDataStatus = null;
		public String CollBoeDialog_MortgageStatus = null;
		public String CollBoeDialog_CoverIndic = null;
		public String CollBoeDialog_CollDataStatus = null;
		public String CollBoeDialog_FinancialFlag = null;
		public String CollBoeDialog_CollateralStatus = null;
		public String CollBoeDialog_WorkflowIndic = null;
		public BigDecimal CollBoeDialog_COL_CAT_ID = null;
		public String save_ver_aut_flag = null;
		public String CollBoeDialog_txtSerLet = null;
		public String CollBoeDialog_txtSerNo = null;
		public BigDecimal CollBoeDialog_CUS_IDInd1 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd2 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd3 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd4 = null;
		public String CollBoeDialog_txtRegNoInd1 = null;
		public String CollBoeDialog_txtRegNoInd2 = null;
		public String CollBoeDialog_txtRegNoInd3 = null;
		public String CollBoeDialog_txtRegNoInd4 = null;
		public String ColBoeLow_txtEligibility = null;
		public String ColBoeRba_txtEligibility = null;
		public String Kol_txtAval = null;
		public BigDecimal cus_id_aval1 = null;
		public String KolBD_txtRegNoAval1 = null;
		public BigDecimal cus_id_aval2 = null;
		public String KolBD_txtRegNoAval2 = null;
		public BigDecimal cus_id_aval3 = null;
		public String KolBD_txtRegNoAval3 = null;
		public BigDecimal cus_id_aval4 = null;
		public String KolBD_txtRegNoAval4 = null;
		public String Kol_txtRbaEligDsc1 = null;
		public BigDecimal CUS_ID = null;
		public Integer Coll_txtNumOf = null;
		public String Kol_txtCRMHnbBoe = null;
		public String Coll_txtB2HNB = null;
		public String Coll_txtB2IRB = null;
		public String Coll_txtContractTypeCode = null;

		// out args
		public BigDecimal CollBoeDialog_COL_HEA_ID = null;
		public String CollBoeDialog_txtColNum = null;
		public Timestamp CollBoeDialog_USER_LOCK = null;
		public BigDecimal CollBoeDialog_BOE_ID = null;
		public String Coll_txtB1Eligibility1 = null;
		public String Coll_txtB1EligDesc1 = null;
		public String Coll_txtB2IRBEligibility1 = null;
		public String Coll_txtB2IRBEligDesc1 = null;
		public String Coll_txtNDEligibility = null;
		public String Coll_txtNDEligDesc = null;
		public String CollBoeDialog_txtEligibility = null;
		public String CollBoeDialog_txtEligDesc = null;
		public BigDecimal Coll_txtRealPonderAmount = null;
		public String Coll_txtWcaOrigCurrencyCode = null;
		public BigDecimal Coll_txtUsedWCAAmount = null;
		public String Coll_txtCollateralGCTCCode = null;
		public String Coll_txtCollateralGCTCDesc = null;
		public String Coll_txtEndorsementTypeGCTCCode = null;
		public String Coll_txtEndorsementTypeGCTCDesc = null;
		public String Coll_txtObjectTypeGCTCCode = null;
		public String Coll_txtObjectTypeGCTCDesc = null;
		public String Coll_txtPropertyTypeGCTCCode = null;
		public String Coll_txtPropertyTypeGCTCDesc = null;
		public BigDecimal Coll_txtB2ValueLLAmount = null;
		public String Coll_txtB2ValueLLCurCode = null;
		public BigDecimal Coll_txtB2ValueGLAmount = null;
		public String Coll_txtB2ValueGLCurCode = null;
		public BigDecimal Coll_txtSumHipToFirstRBA = null;

		public COLLBOEINSERTMAPPING(Map request) {
			setRequest(request);
		}

		public void setRequest(Map request) {
			CollBoeDialog_txtColDesc = (String) request.get("CollBoeDialog_txtColDesc");
			CollBoeDialog_COL_TYPE_ID = (BigDecimal) request.get("CollBoeDialog_COL_TYPE_ID");
			CollBoeDialog_txtCollTypeCode = (String) request.get("CollBoeDialog_txtCollTypeCode");
			CollBoeDialog_txtCollTypeName = (String) request.get("CollBoeDialog_txtCollTypeName");
			CollBoeDialog_CUS_ID = (BigDecimal) request.get("CollBoeDialog_CUS_ID");
			CollBoeDialog_txtRegNoB = (String) request.get("CollBoeDialog_txtRegNoB");
			CollBoeDialog_txtCodeB = (String) request.get("CollBoeDialog_txtCodeB");
			CollBoeDialog_txtNameB = (String) request.get("CollBoeDialog_txtNameB");
			CollBoeDialog_BOE_TYPE_ID = (BigDecimal) request.get("CollBoeDialog_BOE_TYPE_ID");
			CollBoeDialog_txtBoeTypeUCV = (String) request.get("CollBoeDialog_txtBoeTypeUCV");
			CollBoeDialog_txtBoeTypeUCD = (String) request.get("CollBoeDialog_txtBoeTypeUCD");
			CollBoeDialog_ISU_PLACE_ID = (BigDecimal) request.get("CollBoeDialog_ISU_PLACE_ID");
			CollBoeDialog_txtIsuPlaCode = (String) request.get("CollBoeDialog_txtIsuPlaCode");
			CollBoeDialog_txtIssuePlace = (String) request.get("CollBoeDialog_txtIssuePlace");
			CollBoeDialog_txtIssueDate = (Date) request.get("CollBoeDialog_txtIssueDate");
			CollBoeDialog_txtAmount = (BigDecimal) request.get("CollBoeDialog_txtAmount");
			CollBoeDialog_CUR_ID = (BigDecimal) request.get("CollBoeDialog_CUR_ID");
			CollBoeDialog_txtCurIdCodeChar = (String) request.get("CollBoeDialog_txtCurIdCodeChar");
			CollBoeDialog_P_CUS_ID = (BigDecimal) request.get("CollBoeDialog_P_CUS_ID");
			CollBoeDialog_txtRegNoP = (String) request.get("CollBoeDialog_txtRegNoP");
			CollBoeDialog_txtCodeP = (String) request.get("CollBoeDialog_txtCodeP");
			CollBoeDialog_txtNamePayee = (String) request.get("CollBoeDialog_txtNamePayee");
			CollBoeDialog_txtPayeeAccno = (String) request.get("CollBoeDialog_txtPayeeAccno");
			CollBoeDialog_txtAddData = (String) request.get("CollBoeDialog_txtAddData");
			CollBoeDialog_txtAddData1 = (String) request.get("CollBoeDialog_txtAddData1");
			CollBoeDialog_TR_CUS_ID = (BigDecimal) request.get("CollBoeDialog_TR_CUS_ID");
			CollBoeDialog_txtRegNoTR = (String) request.get("CollBoeDialog_txtRegNoTR");
			CollBoeDialog_txtCodeTR = (String) request.get("CollBoeDialog_txtCodeTR");
			CollBoeDialog_txtNameTR = (String) request.get("CollBoeDialog_txtNameTR");
			CollBoeDialog_txtFNameTR = (String) request.get("CollBoeDialog_txtFNameTR");
			CollBoeDialog_txtSNameTR = (String) request.get("CollBoeDialog_txtSNameTR");
			CollBoeDialog_PAY_PLACE_ID = (BigDecimal) request.get("CollBoeDialog_PAY_PLACE_ID");
			CollBoeDialog_txtPayPlaceCode = (String) request.get("CollBoeDialog_txtPayPlaceCode");
			CollBoeDialog_txtPayPlace = (String) request.get("CollBoeDialog_txtPayPlace");
			CollBoeDialog_txtPayment = (String) request.get("CollBoeDialog_txtPayment");
			CollBoeDialog_COLL_CUS_ID = (BigDecimal) request.get("CollBoeDialog_COLL_CUS_ID");
			CollBoeDialog_txtRegNoT = (String) request.get("CollBoeDialog_txtRegNoT");
			CollBoeDialog_txtCodeT = (String) request.get("CollBoeDialog_txtCodeT");
			CollBoeDialog_txtNameT = (String) request.get("CollBoeDialog_txtNameT");
			CollBoeDialog_txtFName = (String) request.get("CollBoeDialog_txtFName");
			CollBoeDialog_txtSName = (String) request.get("CollBoeDialog_txtSName");
			CollBoeDialog_txtNumberClause = (String) request.get("CollBoeDialog_txtNumberClause");
			CollBoeDialog_txtNumberBoe = (Integer) request.get("CollBoeDialog_txtNumberBoe");
			CollBoeDialog_txtMaturityClause = (String) request.get("CollBoeDialog_txtMaturityClause");
			CollBoeDialog_txtMaturityDate = (Date) request.get("CollBoeDialog_txtMaturityDate");
			CollBoeDialog_txtPaymentClause = (String) request.get("CollBoeDialog_txtPaymentClause");
			CollBoeDialog_txtProtestClause = (String) request.get("CollBoeDialog_txtProtestClause");
			CollBoeDialog_txtFeeClause = (String) request.get("CollBoeDialog_txtFeeClause");
			CollBoeDialog_txtReportClause = (String) request.get("CollBoeDialog_txtReportClause");
			CollBoeDialog_txtIndosaClause = (String) request.get("CollBoeDialog_txtIndosaClause");
			CollBoeDialog_txtCureClause = (String) request.get("CollBoeDialog_txtCureClause");
			CollBoeDialog_txtDATE_FROM = (Date) request.get("CollBoeDialog_txtDATE_FROM");
			CollBoeDialog_txtDATE_UNTIL = (Date) request.get("CollBoeDialog_txtDATE_UNTIL");
			CollBoeDialog_Status = (String) request.get("CollBoeDialog_Status");
			CollBoeDialog_StatusDesc = (String) request.get("CollBoeDialog_StatusDesc");
			CollBoeDialog_SpecStatus = (String) request.get("CollBoeDialog_SpecStatus");
			CollBoeDialog_SpecStatusDesc = (String) request.get("CollBoeDialog_SpecStatusDesc");
			CollBoeDialog_USE_OPEN_ID = (BigDecimal) request.get("CollBoeDialog_USE_OPEN_ID");
			CollBoeDialog_USE_ID = (BigDecimal) request.get("CollBoeDialog_USE_ID");
			CollBoeDialog_LA_ACC_ID = (BigDecimal) request.get("CollBoeDialog_LA_ACC_ID");
			CollBoeDialog_txtAccNoLoan = (String) request.get("CollBoeDialog_txtAccNoLoan");
			CollBoeDialog_PAYEE_ADD_ID = (BigDecimal) request.get("CollBoeDialog_PAYEE_ADD_ID");
			CollBoeDialog_txtPayeeFname = (String) request.get("CollBoeDialog_txtPayeeFname");
			CollBoeDialog_txtPayeeSname = (String) request.get("CollBoeDialog_txtPayeeSname");
			CollBoeDialog_ORIGIN_ORG_UNI_ID = (BigDecimal) request.get("CollBoeDialog_ORIGIN_ORG_UNI_ID");
			CollBoeDialog_ORG_UNI_ID = (BigDecimal) request.get("CollBoeDialog_ORG_UNI_ID");
			CollBoeDialog_USE_ID_VER_SND = (BigDecimal) request.get("CollBoeDialog_USE_ID_VER_SND");
			CollBoeDialog_VER_SEND_TS = (Timestamp) request.get("CollBoeDialog_VER_SEND_TS");
			CollBoeDialog_USE_ID_VER = (BigDecimal) request.get("CollBoeDialog_USE_ID_VER");
			CollBoeDialog_VERIFICATION_TS = (Timestamp) request.get("CollBoeDialog_VERIFICATION_TS");
			CollBoeDialog_USE_ID_AUT = (BigDecimal) request.get("CollBoeDialog_USE_ID_AUT");
			CollBoeDialog_AUTORIZATION_TS = (Timestamp) request.get("CollBoeDialog_AUTORIZATION_TS");
			CollBoeDialog_BasicDataStatus = (String) request.get("CollBoeDialog_BasicDataStatus");
			CollBoeDialog_MortgageStatus = (String) request.get("CollBoeDialog_MortgageStatus");
			CollBoeDialog_CoverIndic = (String) request.get("CollBoeDialog_CoverIndic");
			CollBoeDialog_CollDataStatus = (String) request.get("CollBoeDialog_CollDataStatus");
			CollBoeDialog_FinancialFlag = (String) request.get("CollBoeDialog_FinancialFlag");
			CollBoeDialog_CollateralStatus = (String) request.get("CollBoeDialog_CollateralStatus");
			CollBoeDialog_WorkflowIndic = (String) request.get("CollBoeDialog_WorkflowIndic");
			CollBoeDialog_COL_CAT_ID = (BigDecimal) request.get("CollBoeDialog_COL_CAT_ID");
			save_ver_aut_flag = (String) request.get("save_ver_aut_flag");
			CollBoeDialog_txtSerLet = (String) request.get("CollBoeDialog_txtSerLet");
			CollBoeDialog_txtSerNo = (String) request.get("CollBoeDialog_txtSerNo");
			CollBoeDialog_CUS_IDInd1 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd1");
			CollBoeDialog_CUS_IDInd2 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd2");
			CollBoeDialog_CUS_IDInd3 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd3");
			CollBoeDialog_CUS_IDInd4 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd4");
			CollBoeDialog_txtRegNoInd1 = (String) request.get("CollBoeDialog_txtRegNoInd1");
			CollBoeDialog_txtRegNoInd2 = (String) request.get("CollBoeDialog_txtRegNoInd2");
			CollBoeDialog_txtRegNoInd3 = (String) request.get("CollBoeDialog_txtRegNoInd3");
			CollBoeDialog_txtRegNoInd4 = (String) request.get("CollBoeDialog_txtRegNoInd4");
			ColBoeLow_txtEligibility = (String) request.get("ColBoeLow_txtEligibility");
			ColBoeRba_txtEligibility = (String) request.get("ColBoeRba_txtEligibility");
			Kol_txtAval = (String) request.get("Kol_txtAval");
			cus_id_aval1 = (BigDecimal) request.get("cus_id_aval1");
			KolBD_txtRegNoAval1 = (String) request.get("KolBD_txtRegNoAval1");
			cus_id_aval2 = (BigDecimal) request.get("cus_id_aval2");
			KolBD_txtRegNoAval2 = (String) request.get("KolBD_txtRegNoAval2");
			cus_id_aval3 = (BigDecimal) request.get("cus_id_aval3");
			KolBD_txtRegNoAval3 = (String) request.get("KolBD_txtRegNoAval3");
			cus_id_aval4 = (BigDecimal) request.get("cus_id_aval4");
			KolBD_txtRegNoAval4 = (String) request.get("KolBD_txtRegNoAval4");
			Kol_txtRbaEligDsc1 = (String) request.get("Kol_txtRbaEligDsc1");
			CUS_ID = (BigDecimal) request.get("CUS_ID");
			Coll_txtNumOf = (Integer) request.get("Coll_txtNumOf");
			Kol_txtCRMHnbBoe = (String) request.get("Kol_txtCRMHnbBoe");
			Coll_txtB2HNB = (String) request.get("Coll_txtB2HNB");
			Coll_txtB2IRB = (String) request.get("Coll_txtB2IRB");
			Coll_txtContractTypeCode = (String) request.get("Coll_txtContractTypeCode");
		}

		public Map getResponse() {
			response.put("CollBoeDialog_COL_HEA_ID", CollBoeDialog_COL_HEA_ID);
			response.put("CollBoeDialog_txtColNum", CollBoeDialog_txtColNum);
			response.put("CollBoeDialog_USER_LOCK", CollBoeDialog_USER_LOCK);
			response.put("CollBoeDialog_BOE_ID", CollBoeDialog_BOE_ID);
			response.put("Coll_txtB1Eligibility1", Coll_txtB1Eligibility1);
			response.put("Coll_txtB1EligDesc1", Coll_txtB1EligDesc1);
			response.put("Coll_txtB2IRBEligibility1", Coll_txtB2IRBEligibility1);
			response.put("Coll_txtB2IRBEligDesc1", Coll_txtB2IRBEligDesc1);
			response.put("Coll_txtNDEligibility", Coll_txtNDEligibility);
			response.put("Coll_txtNDEligDesc", Coll_txtNDEligDesc);
			response.put("CollBoeDialog_txtEligibility", CollBoeDialog_txtEligibility);
			response.put("CollBoeDialog_txtEligDesc", CollBoeDialog_txtEligDesc);
			response.put("Coll_txtRealPonderAmount", Coll_txtRealPonderAmount);
			response.put("Coll_txtWcaOrigCurrencyCode", Coll_txtWcaOrigCurrencyCode);
			response.put("Coll_txtUsedWCAAmount", Coll_txtUsedWCAAmount);
			response.put("Coll_txtCollateralGCTCCode", Coll_txtCollateralGCTCCode);
			response.put("Coll_txtCollateralGCTCDesc", Coll_txtCollateralGCTCDesc);
			response.put("Coll_txtEndorsementTypeGCTCCode", Coll_txtEndorsementTypeGCTCCode);
			response.put("Coll_txtEndorsementTypeGCTCDesc", Coll_txtEndorsementTypeGCTCDesc);
			response.put("Coll_txtObjectTypeGCTCCode", Coll_txtObjectTypeGCTCCode);
			response.put("Coll_txtObjectTypeGCTCDesc", Coll_txtObjectTypeGCTCDesc);
			response.put("Coll_txtPropertyTypeGCTCCode", Coll_txtPropertyTypeGCTCCode);
			response.put("Coll_txtPropertyTypeGCTCDesc", Coll_txtPropertyTypeGCTCDesc);
			response.put("Coll_txtB2ValueLLAmount", Coll_txtB2ValueLLAmount);
			response.put("Coll_txtB2ValueLLCurCode", Coll_txtB2ValueLLCurCode);
			response.put("Coll_txtB2ValueGLAmount", Coll_txtB2ValueGLAmount);
			response.put("Coll_txtB2ValueGLCurCode", Coll_txtB2ValueGLCurCode);
			response.put("Coll_txtSumHipToFirstRBA", Coll_txtSumHipToFirstRBA);

			return response;
		}

		public Map getRefToResponseMap() {
			return response;
		}

	}

	public class COLLBOEDETAILMAPPING implements MappingDecl {
		public Map response = new HashMap();

		// in args
		public BigDecimal CollBoeDialog_COL_HEA_ID = null;

		// out args
		public String CollBoeDialog_txtColNum = null;
		public String CollBoeDialog_txtColDesc = null;
		public BigDecimal CollBoeDialog_COL_TYPE_ID = null;
		public String CollBoeDialog_txtCollTypeCode = null;
		public String CollBoeDialog_txtCollTypeName = null;
		public BigDecimal CollBoeDialog_CUS_ID = null;
		public String CollBoeDialog_txtRegNoB = null;
		public String CollBoeDialog_txtCodeB = null;
		public String CollBoeDialog_txtNameB = null;
		public BigDecimal CollBoeDialog_BOE_TYPE_ID = null;
		public String CollBoeDialog_txtBoeTypeUCV = null;
		public String CollBoeDialog_txtBoeTypeUCD = null;
		public BigDecimal CollBoeDialog_ISU_PLACE_ID = null;
		public String CollBoeDialog_txtIsuPlaCode = null;
		public String CollBoeDialog_txtIssuePlace = null;
		public Date CollBoeDialog_txtIssueDate = null;
		public BigDecimal CollBoeDialog_txtAmount = null;
		public BigDecimal CollBoeDialog_CUR_ID = null;
		public String CollBoeDialog_txtCurIdCodeChar = null;
		public BigDecimal CollBoeDialog_P_CUS_ID = null;
		public String CollBoeDialog_txtRegNoP = null;
		public String CollBoeDialog_txtCodeP = null;
		public String CollBoeDialog_txtNamePayee = null;
		public String CollBoeDialog_txtPayeeAccno = null;
		public String CollBoeDialog_txtAddData = null;
		public String CollBoeDialog_txtAddData1 = null;
		public BigDecimal CollBoeDialog_TR_CUS_ID = null;
		public String CollBoeDialog_txtRegNoTR = null;
		public String CollBoeDialog_txtCodeTR = null;
		public String CollBoeDialog_txtNameTR = null;
		public String CollBoeDialog_txtFNameTR = null;
		public String CollBoeDialog_txtSNameTR = null;
		public BigDecimal CollBoeDialog_PAY_PLACE_ID = null;
		public String CollBoeDialog_txtPayPlaceCode = null;
		public String CollBoeDialog_txtPayPlace = null;
		public String CollBoeDialog_txtPayment = null;
		public BigDecimal CollBoeDialog_COLL_CUS_ID = null;
		public String CollBoeDialog_txtRegNoT = null;
		public String CollBoeDialog_txtCodeT = null;
		public String CollBoeDialog_txtNameT = null;
		public String CollBoeDialog_txtFName = null;
		public String CollBoeDialog_txtSName = null;
		public String CollBoeDialog_txtNumberClause = null;
		public Integer CollBoeDialog_txtNumberBoe = null;
		public String CollBoeDialog_txtMaturityClause = null;
		public Date CollBoeDialog_txtMaturityDate = null;
		public String CollBoeDialog_txtPaymentClause = null;
		public String CollBoeDialog_txtProtestClause = null;
		public String CollBoeDialog_txtFeeClause = null;
		public String CollBoeDialog_txtReportClause = null;
		public String CollBoeDialog_txtIndosaClause = null;
		public String CollBoeDialog_txtCureClause = null;
		public BigDecimal CollBoeDialog_BOE_ID = null;
		public String CollBoeDialog_txtEligibility = null;
		public String CollBoeDialog_txtEligDesc = null;
		public Date CollBoeDialog_txtDATE_FROM = null;
		public Date CollBoeDialog_txtDATE_UNTIL = null;
		public String CollBoeDialog_Status = null;
		public String CollBoeDialog_StatusDesc = null;
		public String CollBoeDialog_SpecStatus = null;
		public String CollBoeDialog_SpecStatusDesc = null;
		public BigDecimal CollBoeDialog_USE_OPEN_ID = null;
		public BigDecimal CollBoeDialog_USE_ID = null;
		public Timestamp CollBoeDialog_OPENING_TS = null;
		public Timestamp CollBoeDialog_USER_LOCK = null;
		public String CollBoeDialog_txtUseOpenIdLogin = null;
		public String CollBoeDialog_txtUseOpenIdName = null;
		public Timestamp CollBoeDialog_txtOpeningTs = null;
		public String CollBoeDialog_txtUseIdLogin = null;
		public String CollBoeDialog_txtUseIdName = null;
		public Timestamp CollBoeDialog_txtUserLock = null;
		public BigDecimal CollBoeDialog_LA_ACC_ID = null;
		public String CollBoeDialog_txtAccNoLoan = null;
		public BigDecimal CollBoeDialog_PAYEE_ADD_ID = null;
		public String CollBoeDialog_txtPayeeFname = null;
		public String CollBoeDialog_txtPayeeSname = null;
		public BigDecimal CollBoeDialog_ORIGIN_ORG_UNI_ID = null;
		public BigDecimal CollBoeDialog_ORG_UNI_ID = null;
		public BigDecimal CollBoeDialog_USE_ID_VER_SND = null;
		public String CollBoeDialog_txtUseIdSenLogin = null;
		public String CollBoeDialog_txtUseIdSenName = null;
		public Timestamp CollBoeDialog_VER_SEND_TS = null;
		public BigDecimal CollBoeDialog_USE_ID_VER = null;
		public String CollBoeDialog_txtUseIdVerLogin = null;
		public String CollBoeDialog_txtUseIdVerName = null;
		public Timestamp CollBoeDialog_VERIFICATION_TS = null;
		public BigDecimal CollBoeDialog_USE_ID_AUT = null;
		public String CollBoeDialog_txtUseIdAutLogin = null;
		public String CollBoeDialog_txtUseIdAutName = null;
		public Timestamp CollBoeDialog_AUTORIZATION_TS = null;
		public String CollBoeDialog_BasicDataStatus = null;
		public String CollBoeDialog_txtBasicDataSt = null;
		public String CollBoeDialog_MortgageStatus = null;
		public String CollBoeDialog_txtMortgageSt = null;
		public String CollBoeDialog_CoverIndic = null;
		public String CollBoeDialog_txtCoverIn = null;
		public String CollBoeDialog_CollDataStatus = null;
		public String CollBoeDialog_txtCollDataSt = null;
		public String CollBoeDialog_FinancialFlag = null;
		public String CollBoeDialog_txtFinancialFl = null;
		public String CollBoeDialog_CollateralStatus = null;
		public String CollBoeDialog_WorkflowIndic = null;
		public BigDecimal CollBoeDialog_COL_CAT_ID = null;
		public String CollBoeDialog_txtSerLet = null;
		public String CollBoeDialog_txtSerNo = null;
		public BigDecimal CollBoeDialog_CUS_IDInd1 = null;
		public String CollBoeDialog_txtRegNoInd1 = null;
		public String CollBoeDialog_txtCodeInd1 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd2 = null;
		public String CollBoeDialog_txtRegNoInd2 = null;
		public String CollBoeDialog_txtCodeInd2 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd3 = null;
		public String CollBoeDialog_txtRegNoInd3 = null;
		public String CollBoeDialog_txtCodeInd3 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd4 = null;
		public String CollBoeDialog_txtRegNoInd4 = null;
		public String CollBoeDialog_txtCodeInd4 = null;
		public String CollBoeDialog_txtNameInd1 = null;
		public String CollBoeDialog_txtFNameInd1 = null;
		public String CollBoeDialog_txtSNameInd1 = null;
		public String CollBoeDialog_txtNameInd2 = null;
		public String CollBoeDialog_txtFNameInd2 = null;
		public String CollBoeDialog_txtSNameInd2 = null;
		public String CollBoeDialog_txtNameInd3 = null;
		public String CollBoeDialog_txtFNameInd3 = null;
		public String CollBoeDialog_txtSNameInd3 = null;
		public String CollBoeDialog_txtNameInd4 = null;
		public String CollBoeDialog_txtFNameInd4 = null;
		public String CollBoeDialog_txtSNameInd4 = null;
		public String CollBoeDialog_txtAddressInd1 = null;
		public String CollBoeDialog_txtPlaceAddressInd1 = null;
		public String CollBoeDialog_txtPostNrInd1 = null;
		public String CollBoeDialog_txtPostNameInd1 = null;
		public String CollBoeDialog_txtAddressInd2 = null;
		public String CollBoeDialog_txtPlaceAddressInd2 = null;
		public String CollBoeDialog_txtPostNrInd2 = null;
		public String CollBoeDialog_txtPostNameInd2 = null;
		public String CollBoeDialog_txtAddressInd3 = null;
		public String CollBoeDialog_txtPlaceAddressInd3 = null;
		public String CollBoeDialog_txtPostNrInd3 = null;
		public String CollBoeDialog_txtPostNameInd3 = null;
		public String CollBoeDialog_txtAddressInd4 = null;
		public String CollBoeDialog_txtPlaceAddressInd4 = null;
		public String CollBoeDialog_txtPostNrInd4 = null;
		public String CollBoeDialog_txtPostNameInd4 = null;
		public String CollBoeDialog_txtAddressT = null;
		public String CollBoeDialog_txtPlaceAddressT = null;
		public String CollBoeDialog_txtPostNrT = null;
		public String CollBoeDialog_txtPostNameT = null;
		public String CollBoeDialog_txtAddressTR = null;
		public String CollBoeDialog_txtPlaceAddressTR = null;
		public String CollBoeDialog_txtPostNrTR = null;
		public String CollBoeDialog_txtPostNameTR = null;
		public String ColBoeLow_txtEligibility = null;
		public String ColBoeLow_txtEligibilityDesc = null;
		public String ColBoeRba_txtEligibilityDsc = null;
		public String ColBoeRba_txtEligibility = null;
		public String Kol_txtAval = null;
		public BigDecimal cus_id_aval1 = null;
		public String CollBoeDialog_txtAddressAv1 = null;
		public String CollBoeDialog_txtPlaceAddressAv1 = null;
		public String KolBD_txtRegNoAval1 = null;
		public String KolBD_txtCodeAval1 = null;
		public String KolBD_txtPostNrAval1 = null;
		public String KolBD_txtPostNameAval1 = null;
		public String KolBD_txtNameAval1 = null;
		public String KolBD_txtFNameAval1 = null;
		public String KolBD_txtSNameAval1 = null;
		public BigDecimal cus_id_aval2 = null;
		public String CollBoeDialog_txtAddressAv2 = null;
		public String CollBoeDialog_txtPlaceAddressAv2 = null;
		public String KolBD_txtRegNoAval2 = null;
		public String KolBD_txtCodeAval2 = null;
		public String KolBD_txtPostNrAval2 = null;
		public String KolBD_txtPostNameAval2 = null;
		public String KolBD_txtNameAval2 = null;
		public String KolBD_txtFNameAval2 = null;
		public String KolBD_txtSNameAval2 = null;
		public BigDecimal cus_id_aval3 = null;
		public String CollBoeDialog_txtAddressAv3 = null;
		public String CollBoeDialog_txtPlaceAddressAv3 = null;
		public String KolBD_txtRegNoAval3 = null;
		public String KolBD_txtCodeAval3 = null;
		public String KolBD_txtPostNrAval3 = null;
		public String KolBD_txtPostNameAval3 = null;
		public String KolBD_txtNameAval3 = null;
		public String KolBD_txtFNameAval3 = null;
		public String KolBD_txtSNameAval3 = null;
		public BigDecimal cus_id_aval4 = null;
		public String CollBoeDialog_txtAddressAv4 = null;
		public String CollBoeDialog_txtPlaceAddressAv4 = null;
		public String KolBD_txtRegNoAval4 = null;
		public String KolBD_txtCodeAval4 = null;
		public String KolBD_txtPostNrAval4 = null;
		public String KolBD_txtPostNameAval4 = null;
		public String KolBD_txtNameAval4 = null;
		public String KolBD_txtFNameAval4 = null;
		public String KolBD_txtSNameAval4 = null;
		public String Kol_txtRbaEligDsc1 = null;
		public BigDecimal CUS_ID = null;
		public Integer Coll_txtNumOf = null;
		public String Coll_txtCarrierRegisterNo = null;
		public String Coll_txtCarrierName = null;
		public String Coll_txtB1Eligibility1 = null;
		public String Coll_txtB1EligDesc1 = null;
		public String Coll_txtB2IRBEligibility1 = null;
		public String Coll_txtB2IRBEligDesc1 = null;
		public String Kol_txtCRMHnbBoe = null;
		public String Coll_txtNDEligibility = null;
		public String Coll_txtNDEligDesc = null;
		public BigDecimal CollBoeDialog_txtWcaAmount = null;
		public Date CollBoeDialog_txtWcaAmountDate = null;
		public String CollBoe_txtCoConfirm = null;
		public String CollBoe_txtCoConfirmUserId = null;
		public String CollBoe_txtCoConfirmUserName = null;
		public Timestamp CollBoe_txtCoConfirmTime = null;
		public BigDecimal Coll_txtCollMvpPonderMin = null;
		public BigDecimal Coll_txtCollMvpPonderMax = null;
		public BigDecimal Coll_txtCollMvpPonder = null;
		public String Coll_txtB2HNB = null;
		public String Coll_txtB2HNB_OLD = null;
		public String Coll_txtB2IRB = null;
		public String Coll_txtB2IRB_OLD = null;
		public BigDecimal Coll_txtRealPonderAmount = null;
		public String Coll_txtContractTypeCode = null;
		public String Coll_txtWcaOrigCurrencyCode = null;
		public BigDecimal Coll_txtUsedWCAAmount = null;
		public String Coll_txtCollateralGCTCCode = null;
		public String Coll_txtCollateralGCTCDesc = null;
		public String Coll_txtEndorsementTypeGCTCCode = null;
		public String Coll_txtEndorsementTypeGCTCDesc = null;
		public String Coll_txtObjectTypeGCTCCode = null;
		public String Coll_txtObjectTypeGCTCDesc = null;
		public String Coll_txtPropertyTypeGCTCCode = null;
		public String Coll_txtPropertyTypeGCTCDesc = null;
		public BigDecimal Coll_txtB2ValueLLAmount = null;
		public String Coll_txtB2ValueLLCurCode = null;
		public BigDecimal Coll_txtB2ValueGLAmount = null;
		public String Coll_txtB2ValueGLCurCode = null;
		public BigDecimal Coll_txtSumHipToFirstRBA = null;
		public BigDecimal Kol_txtPonderMVP = null;

		public COLLBOEDETAILMAPPING(Map request) {
			setRequest(request);
		}

		public void setRequest(Map request) {
			CollBoeDialog_COL_HEA_ID = (BigDecimal) request.get("CollBoeDialog_COL_HEA_ID");
		}

		public Map getResponse() {
			response.put("CollBoeDialog_txtColNum", CollBoeDialog_txtColNum);
			response.put("CollBoeDialog_txtColDesc", CollBoeDialog_txtColDesc);
			response.put("CollBoeDialog_COL_TYPE_ID", CollBoeDialog_COL_TYPE_ID);
			response.put("CollBoeDialog_txtCollTypeCode", CollBoeDialog_txtCollTypeCode);
			response.put("CollBoeDialog_txtCollTypeName", CollBoeDialog_txtCollTypeName);
			response.put("CollBoeDialog_CUS_ID", CollBoeDialog_CUS_ID);
			response.put("CollBoeDialog_txtRegNoB", CollBoeDialog_txtRegNoB);
			response.put("CollBoeDialog_txtCodeB", CollBoeDialog_txtCodeB);
			response.put("CollBoeDialog_txtNameB", CollBoeDialog_txtNameB);
			response.put("CollBoeDialog_BOE_TYPE_ID", CollBoeDialog_BOE_TYPE_ID);
			response.put("CollBoeDialog_txtBoeTypeUCV", CollBoeDialog_txtBoeTypeUCV);
			response.put("CollBoeDialog_txtBoeTypeUCD", CollBoeDialog_txtBoeTypeUCD);
			response.put("CollBoeDialog_ISU_PLACE_ID", CollBoeDialog_ISU_PLACE_ID);
			response.put("CollBoeDialog_txtIsuPlaCode", CollBoeDialog_txtIsuPlaCode);
			response.put("CollBoeDialog_txtIssuePlace", CollBoeDialog_txtIssuePlace);
			response.put("CollBoeDialog_txtIssueDate", CollBoeDialog_txtIssueDate);
			response.put("CollBoeDialog_txtAmount", CollBoeDialog_txtAmount);
			response.put("CollBoeDialog_CUR_ID", CollBoeDialog_CUR_ID);
			response.put("CollBoeDialog_txtCurIdCodeChar", CollBoeDialog_txtCurIdCodeChar);
			response.put("CollBoeDialog_P_CUS_ID", CollBoeDialog_P_CUS_ID);
			response.put("CollBoeDialog_txtRegNoP", CollBoeDialog_txtRegNoP);
			response.put("CollBoeDialog_txtCodeP", CollBoeDialog_txtCodeP);
			response.put("CollBoeDialog_txtNamePayee", CollBoeDialog_txtNamePayee);
			response.put("CollBoeDialog_txtPayeeAccno", CollBoeDialog_txtPayeeAccno);
			response.put("CollBoeDialog_txtAddData", CollBoeDialog_txtAddData);
			response.put("CollBoeDialog_txtAddData1", CollBoeDialog_txtAddData1);
			response.put("CollBoeDialog_TR_CUS_ID", CollBoeDialog_TR_CUS_ID);
			response.put("CollBoeDialog_txtRegNoTR", CollBoeDialog_txtRegNoTR);
			response.put("CollBoeDialog_txtCodeTR", CollBoeDialog_txtCodeTR);
			response.put("CollBoeDialog_txtNameTR", CollBoeDialog_txtNameTR);
			response.put("CollBoeDialog_txtFNameTR", CollBoeDialog_txtFNameTR);
			response.put("CollBoeDialog_txtSNameTR", CollBoeDialog_txtSNameTR);
			response.put("CollBoeDialog_PAY_PLACE_ID", CollBoeDialog_PAY_PLACE_ID);
			response.put("CollBoeDialog_txtPayPlaceCode", CollBoeDialog_txtPayPlaceCode);
			response.put("CollBoeDialog_txtPayPlace", CollBoeDialog_txtPayPlace);
			response.put("CollBoeDialog_txtPayment", CollBoeDialog_txtPayment);
			response.put("CollBoeDialog_COLL_CUS_ID", CollBoeDialog_COLL_CUS_ID);
			response.put("CollBoeDialog_txtRegNoT", CollBoeDialog_txtRegNoT);
			response.put("CollBoeDialog_txtCodeT", CollBoeDialog_txtCodeT);
			response.put("CollBoeDialog_txtNameT", CollBoeDialog_txtNameT);
			response.put("CollBoeDialog_txtFName", CollBoeDialog_txtFName);
			response.put("CollBoeDialog_txtSName", CollBoeDialog_txtSName);
			response.put("CollBoeDialog_txtNumberClause", CollBoeDialog_txtNumberClause);
			response.put("CollBoeDialog_txtNumberBoe", CollBoeDialog_txtNumberBoe);
			response.put("CollBoeDialog_txtMaturityClause", CollBoeDialog_txtMaturityClause);
			response.put("CollBoeDialog_txtMaturityDate", CollBoeDialog_txtMaturityDate);
			response.put("CollBoeDialog_txtPaymentClause", CollBoeDialog_txtPaymentClause);
			response.put("CollBoeDialog_txtProtestClause", CollBoeDialog_txtProtestClause);
			response.put("CollBoeDialog_txtFeeClause", CollBoeDialog_txtFeeClause);
			response.put("CollBoeDialog_txtReportClause", CollBoeDialog_txtReportClause);
			response.put("CollBoeDialog_txtIndosaClause", CollBoeDialog_txtIndosaClause);
			response.put("CollBoeDialog_txtCureClause", CollBoeDialog_txtCureClause);
			response.put("CollBoeDialog_BOE_ID", CollBoeDialog_BOE_ID);
			response.put("CollBoeDialog_txtEligibility", CollBoeDialog_txtEligibility);
			response.put("CollBoeDialog_txtEligDesc", CollBoeDialog_txtEligDesc);
			response.put("CollBoeDialog_txtDATE_FROM", CollBoeDialog_txtDATE_FROM);
			response.put("CollBoeDialog_txtDATE_UNTIL", CollBoeDialog_txtDATE_UNTIL);
			response.put("CollBoeDialog_Status", CollBoeDialog_Status);
			response.put("CollBoeDialog_StatusDesc", CollBoeDialog_StatusDesc);
			response.put("CollBoeDialog_SpecStatus", CollBoeDialog_SpecStatus);
			response.put("CollBoeDialog_SpecStatusDesc", CollBoeDialog_SpecStatusDesc);
			response.put("CollBoeDialog_USE_OPEN_ID", CollBoeDialog_USE_OPEN_ID);
			response.put("CollBoeDialog_USE_ID", CollBoeDialog_USE_ID);
			response.put("CollBoeDialog_OPENING_TS", CollBoeDialog_OPENING_TS);
			response.put("CollBoeDialog_USER_LOCK", CollBoeDialog_USER_LOCK);
			response.put("CollBoeDialog_txtUseOpenIdLogin", CollBoeDialog_txtUseOpenIdLogin);
			response.put("CollBoeDialog_txtUseOpenIdName", CollBoeDialog_txtUseOpenIdName);
			response.put("CollBoeDialog_txtOpeningTs", CollBoeDialog_txtOpeningTs);
			response.put("CollBoeDialog_txtUseIdLogin", CollBoeDialog_txtUseIdLogin);
			response.put("CollBoeDialog_txtUseIdName", CollBoeDialog_txtUseIdName);
			response.put("CollBoeDialog_txtUserLock", CollBoeDialog_txtUserLock);
			response.put("CollBoeDialog_LA_ACC_ID", CollBoeDialog_LA_ACC_ID);
			response.put("CollBoeDialog_txtAccNoLoan", CollBoeDialog_txtAccNoLoan);
			response.put("CollBoeDialog_PAYEE_ADD_ID", CollBoeDialog_PAYEE_ADD_ID);
			response.put("CollBoeDialog_txtPayeeFname", CollBoeDialog_txtPayeeFname);
			response.put("CollBoeDialog_txtPayeeSname", CollBoeDialog_txtPayeeSname);
			response.put("CollBoeDialog_ORIGIN_ORG_UNI_ID", CollBoeDialog_ORIGIN_ORG_UNI_ID);
			response.put("CollBoeDialog_ORG_UNI_ID", CollBoeDialog_ORG_UNI_ID);
			response.put("CollBoeDialog_USE_ID_VER_SND", CollBoeDialog_USE_ID_VER_SND);
			response.put("CollBoeDialog_txtUseIdSenLogin", CollBoeDialog_txtUseIdSenLogin);
			response.put("CollBoeDialog_txtUseIdSenName", CollBoeDialog_txtUseIdSenName);
			response.put("CollBoeDialog_VER_SEND_TS", CollBoeDialog_VER_SEND_TS);
			response.put("CollBoeDialog_USE_ID_VER", CollBoeDialog_USE_ID_VER);
			response.put("CollBoeDialog_txtUseIdVerLogin", CollBoeDialog_txtUseIdVerLogin);
			response.put("CollBoeDialog_txtUseIdVerName", CollBoeDialog_txtUseIdVerName);
			response.put("CollBoeDialog_VERIFICATION_TS", CollBoeDialog_VERIFICATION_TS);
			response.put("CollBoeDialog_USE_ID_AUT", CollBoeDialog_USE_ID_AUT);
			response.put("CollBoeDialog_txtUseIdAutLogin", CollBoeDialog_txtUseIdAutLogin);
			response.put("CollBoeDialog_txtUseIdAutName", CollBoeDialog_txtUseIdAutName);
			response.put("CollBoeDialog_AUTORIZATION_TS", CollBoeDialog_AUTORIZATION_TS);
			response.put("CollBoeDialog_BasicDataStatus", CollBoeDialog_BasicDataStatus);
			response.put("CollBoeDialog_txtBasicDataSt", CollBoeDialog_txtBasicDataSt);
			response.put("CollBoeDialog_MortgageStatus", CollBoeDialog_MortgageStatus);
			response.put("CollBoeDialog_txtMortgageSt", CollBoeDialog_txtMortgageSt);
			response.put("CollBoeDialog_CoverIndic", CollBoeDialog_CoverIndic);
			response.put("CollBoeDialog_txtCoverIn", CollBoeDialog_txtCoverIn);
			response.put("CollBoeDialog_CollDataStatus", CollBoeDialog_CollDataStatus);
			response.put("CollBoeDialog_txtCollDataSt", CollBoeDialog_txtCollDataSt);
			response.put("CollBoeDialog_FinancialFlag", CollBoeDialog_FinancialFlag);
			response.put("CollBoeDialog_txtFinancialFl", CollBoeDialog_txtFinancialFl);
			response.put("CollBoeDialog_CollateralStatus", CollBoeDialog_CollateralStatus);
			response.put("CollBoeDialog_WorkflowIndic", CollBoeDialog_WorkflowIndic);
			response.put("CollBoeDialog_COL_CAT_ID", CollBoeDialog_COL_CAT_ID);
			response.put("CollBoeDialog_txtSerLet", CollBoeDialog_txtSerLet);
			response.put("CollBoeDialog_txtSerNo", CollBoeDialog_txtSerNo);
			response.put("CollBoeDialog_CUS_IDInd1", CollBoeDialog_CUS_IDInd1);
			response.put("CollBoeDialog_txtRegNoInd1", CollBoeDialog_txtRegNoInd1);
			response.put("CollBoeDialog_txtCodeInd1", CollBoeDialog_txtCodeInd1);
			response.put("CollBoeDialog_CUS_IDInd2", CollBoeDialog_CUS_IDInd2);
			response.put("CollBoeDialog_txtRegNoInd2", CollBoeDialog_txtRegNoInd2);
			response.put("CollBoeDialog_txtCodeInd2", CollBoeDialog_txtCodeInd2);
			response.put("CollBoeDialog_CUS_IDInd3", CollBoeDialog_CUS_IDInd3);
			response.put("CollBoeDialog_txtRegNoInd3", CollBoeDialog_txtRegNoInd3);
			response.put("CollBoeDialog_txtCodeInd3", CollBoeDialog_txtCodeInd3);
			response.put("CollBoeDialog_CUS_IDInd4", CollBoeDialog_CUS_IDInd4);
			response.put("CollBoeDialog_txtRegNoInd4", CollBoeDialog_txtRegNoInd4);
			response.put("CollBoeDialog_txtCodeInd4", CollBoeDialog_txtCodeInd4);
			response.put("CollBoeDialog_txtNameInd1", CollBoeDialog_txtNameInd1);
			response.put("CollBoeDialog_txtFNameInd1", CollBoeDialog_txtFNameInd1);
			response.put("CollBoeDialog_txtSNameInd1", CollBoeDialog_txtSNameInd1);
			response.put("CollBoeDialog_txtNameInd2", CollBoeDialog_txtNameInd2);
			response.put("CollBoeDialog_txtFNameInd2", CollBoeDialog_txtFNameInd2);
			response.put("CollBoeDialog_txtSNameInd2", CollBoeDialog_txtSNameInd2);
			response.put("CollBoeDialog_txtNameInd3", CollBoeDialog_txtNameInd3);
			response.put("CollBoeDialog_txtFNameInd3", CollBoeDialog_txtFNameInd3);
			response.put("CollBoeDialog_txtSNameInd3", CollBoeDialog_txtSNameInd3);
			response.put("CollBoeDialog_txtNameInd4", CollBoeDialog_txtNameInd4);
			response.put("CollBoeDialog_txtFNameInd4", CollBoeDialog_txtFNameInd4);
			response.put("CollBoeDialog_txtSNameInd4", CollBoeDialog_txtSNameInd4);
			response.put("CollBoeDialog_txtAddressInd1", CollBoeDialog_txtAddressInd1);
			response.put("CollBoeDialog_txtPlaceAddressInd1", CollBoeDialog_txtPlaceAddressInd1);
			response.put("CollBoeDialog_txtPostNrInd1", CollBoeDialog_txtPostNrInd1);
			response.put("CollBoeDialog_txtPostNameInd1", CollBoeDialog_txtPostNameInd1);
			response.put("CollBoeDialog_txtAddressInd2", CollBoeDialog_txtAddressInd2);
			response.put("CollBoeDialog_txtPlaceAddressInd2", CollBoeDialog_txtPlaceAddressInd2);
			response.put("CollBoeDialog_txtPostNrInd2", CollBoeDialog_txtPostNrInd2);
			response.put("CollBoeDialog_txtPostNameInd2", CollBoeDialog_txtPostNameInd2);
			response.put("CollBoeDialog_txtAddressInd3", CollBoeDialog_txtAddressInd3);
			response.put("CollBoeDialog_txtPlaceAddressInd3", CollBoeDialog_txtPlaceAddressInd3);
			response.put("CollBoeDialog_txtPostNrInd3", CollBoeDialog_txtPostNrInd3);
			response.put("CollBoeDialog_txtPostNameInd3", CollBoeDialog_txtPostNameInd3);
			response.put("CollBoeDialog_txtAddressInd4", CollBoeDialog_txtAddressInd4);
			response.put("CollBoeDialog_txtPlaceAddressInd4", CollBoeDialog_txtPlaceAddressInd4);
			response.put("CollBoeDialog_txtPostNrInd4", CollBoeDialog_txtPostNrInd4);
			response.put("CollBoeDialog_txtPostNameInd4", CollBoeDialog_txtPostNameInd4);
			response.put("CollBoeDialog_txtAddressT", CollBoeDialog_txtAddressT);
			response.put("CollBoeDialog_txtPlaceAddressT", CollBoeDialog_txtPlaceAddressT);
			response.put("CollBoeDialog_txtPostNrT", CollBoeDialog_txtPostNrT);
			response.put("CollBoeDialog_txtPostNameT", CollBoeDialog_txtPostNameT);
			response.put("CollBoeDialog_txtAddressTR", CollBoeDialog_txtAddressTR);
			response.put("CollBoeDialog_txtPlaceAddressTR", CollBoeDialog_txtPlaceAddressTR);
			response.put("CollBoeDialog_txtPostNrTR", CollBoeDialog_txtPostNrTR);
			response.put("CollBoeDialog_txtPostNameTR", CollBoeDialog_txtPostNameTR);
			response.put("ColBoeLow_txtEligibility", ColBoeLow_txtEligibility);
			response.put("ColBoeLow_txtEligibilityDesc", ColBoeLow_txtEligibilityDesc);
			response.put("ColBoeRba_txtEligibilityDsc", ColBoeRba_txtEligibilityDsc);
			response.put("ColBoeRba_txtEligibility", ColBoeRba_txtEligibility);
			response.put("Kol_txtAval", Kol_txtAval);
			response.put("cus_id_aval1", cus_id_aval1);
			response.put("CollBoeDialog_txtAddressAv1", CollBoeDialog_txtAddressAv1);
			response.put("CollBoeDialog_txtPlaceAddressAv1", CollBoeDialog_txtPlaceAddressAv1);
			response.put("KolBD_txtRegNoAval1", KolBD_txtRegNoAval1);
			response.put("KolBD_txtCodeAval1", KolBD_txtCodeAval1);
			response.put("KolBD_txtPostNrAval1", KolBD_txtPostNrAval1);
			response.put("KolBD_txtPostNameAval1", KolBD_txtPostNameAval1);
			response.put("KolBD_txtNameAval1", KolBD_txtNameAval1);
			response.put("KolBD_txtFNameAval1", KolBD_txtFNameAval1);
			response.put("KolBD_txtSNameAval1", KolBD_txtSNameAval1);
			response.put("cus_id_aval2", cus_id_aval2);
			response.put("CollBoeDialog_txtAddressAv2", CollBoeDialog_txtAddressAv2);
			response.put("CollBoeDialog_txtPlaceAddressAv2", CollBoeDialog_txtPlaceAddressAv2);
			response.put("KolBD_txtRegNoAval2", KolBD_txtRegNoAval2);
			response.put("KolBD_txtCodeAval2", KolBD_txtCodeAval2);
			response.put("KolBD_txtPostNrAval2", KolBD_txtPostNrAval2);
			response.put("KolBD_txtPostNameAval2", KolBD_txtPostNameAval2);
			response.put("KolBD_txtNameAval2", KolBD_txtNameAval2);
			response.put("KolBD_txtFNameAval2", KolBD_txtFNameAval2);
			response.put("KolBD_txtSNameAval2", KolBD_txtSNameAval2);
			response.put("cus_id_aval3", cus_id_aval3);
			response.put("CollBoeDialog_txtAddressAv3", CollBoeDialog_txtAddressAv3);
			response.put("CollBoeDialog_txtPlaceAddressAv3", CollBoeDialog_txtPlaceAddressAv3);
			response.put("KolBD_txtRegNoAval3", KolBD_txtRegNoAval3);
			response.put("KolBD_txtCodeAval3", KolBD_txtCodeAval3);
			response.put("KolBD_txtPostNrAval3", KolBD_txtPostNrAval3);
			response.put("KolBD_txtPostNameAval3", KolBD_txtPostNameAval3);
			response.put("KolBD_txtNameAval3", KolBD_txtNameAval3);
			response.put("KolBD_txtFNameAval3", KolBD_txtFNameAval3);
			response.put("KolBD_txtSNameAval3", KolBD_txtSNameAval3);
			response.put("cus_id_aval4", cus_id_aval4);
			response.put("CollBoeDialog_txtAddressAv4", CollBoeDialog_txtAddressAv4);
			response.put("CollBoeDialog_txtPlaceAddressAv4", CollBoeDialog_txtPlaceAddressAv4);
			response.put("KolBD_txtRegNoAval4", KolBD_txtRegNoAval4);
			response.put("KolBD_txtCodeAval4", KolBD_txtCodeAval4);
			response.put("KolBD_txtPostNrAval4", KolBD_txtPostNrAval4);
			response.put("KolBD_txtPostNameAval4", KolBD_txtPostNameAval4);
			response.put("KolBD_txtNameAval4", KolBD_txtNameAval4);
			response.put("KolBD_txtFNameAval4", KolBD_txtFNameAval4);
			response.put("KolBD_txtSNameAval4", KolBD_txtSNameAval4);
			response.put("Kol_txtRbaEligDsc1", Kol_txtRbaEligDsc1);
			response.put("CUS_ID", CUS_ID);
			response.put("Coll_txtNumOf", Coll_txtNumOf);
			response.put("Coll_txtCarrierRegisterNo", Coll_txtCarrierRegisterNo);
			response.put("Coll_txtCarrierName", Coll_txtCarrierName);
			response.put("Coll_txtB1Eligibility1", Coll_txtB1Eligibility1);
			response.put("Coll_txtB1EligDesc1", Coll_txtB1EligDesc1);
			response.put("Coll_txtB2IRBEligibility1", Coll_txtB2IRBEligibility1);
			response.put("Coll_txtB2IRBEligDesc1", Coll_txtB2IRBEligDesc1);
			response.put("Kol_txtCRMHnbBoe", Kol_txtCRMHnbBoe);
			response.put("Coll_txtNDEligibility", Coll_txtNDEligibility);
			response.put("Coll_txtNDEligDesc", Coll_txtNDEligDesc);
			response.put("CollBoeDialog_txtWcaAmount", CollBoeDialog_txtWcaAmount);
			response.put("CollBoeDialog_txtWcaAmountDate", CollBoeDialog_txtWcaAmountDate);
			response.put("CollBoe_txtCoConfirm", CollBoe_txtCoConfirm);
			response.put("CollBoe_txtCoConfirmUserId", CollBoe_txtCoConfirmUserId);
			response.put("CollBoe_txtCoConfirmUserName", CollBoe_txtCoConfirmUserName);
			response.put("CollBoe_txtCoConfirmTime", CollBoe_txtCoConfirmTime);
			response.put("Coll_txtCollMvpPonderMin", Coll_txtCollMvpPonderMin);
			response.put("Coll_txtCollMvpPonderMax", Coll_txtCollMvpPonderMax);
			response.put("Coll_txtCollMvpPonder", Coll_txtCollMvpPonder);
			response.put("Coll_txtB2HNB", Coll_txtB2HNB);
			response.put("Coll_txtB2HNB_OLD", Coll_txtB2HNB_OLD);
			response.put("Coll_txtB2IRB", Coll_txtB2IRB);
			response.put("Coll_txtB2IRB_OLD", Coll_txtB2IRB_OLD);
			response.put("Coll_txtRealPonderAmount", Coll_txtRealPonderAmount);
			response.put("Coll_txtContractTypeCode", Coll_txtContractTypeCode);
			response.put("Coll_txtWcaOrigCurrencyCode", Coll_txtWcaOrigCurrencyCode);
			response.put("Coll_txtUsedWCAAmount", Coll_txtUsedWCAAmount);
			response.put("Coll_txtCollateralGCTCCode", Coll_txtCollateralGCTCCode);
			response.put("Coll_txtCollateralGCTCDesc", Coll_txtCollateralGCTCDesc);
			response.put("Coll_txtEndorsementTypeGCTCCode", Coll_txtEndorsementTypeGCTCCode);
			response.put("Coll_txtEndorsementTypeGCTCDesc", Coll_txtEndorsementTypeGCTCDesc);
			response.put("Coll_txtObjectTypeGCTCCode", Coll_txtObjectTypeGCTCCode);
			response.put("Coll_txtObjectTypeGCTCDesc", Coll_txtObjectTypeGCTCDesc);
			response.put("Coll_txtPropertyTypeGCTCCode", Coll_txtPropertyTypeGCTCCode);
			response.put("Coll_txtPropertyTypeGCTCDesc", Coll_txtPropertyTypeGCTCDesc);
			response.put("Coll_txtB2ValueLLAmount", Coll_txtB2ValueLLAmount);
			response.put("Coll_txtB2ValueLLCurCode", Coll_txtB2ValueLLCurCode);
			response.put("Coll_txtB2ValueGLAmount", Coll_txtB2ValueGLAmount);
			response.put("Coll_txtB2ValueGLCurCode", Coll_txtB2ValueGLCurCode);
			response.put("Coll_txtSumHipToFirstRBA", Coll_txtSumHipToFirstRBA);
			response.put("Kol_txtPonderMVP", Kol_txtPonderMVP);

			return response;
		}

		public Map getRefToResponseMap() {
			return response;
		}

	}

	public class COLLBOEUPDATEMAPPING implements MappingDecl {
		public Map response = new HashMap();

		// in args
		public BigDecimal CollBoeDialog_COL_HEA_ID = null;
		public String CollBoeDialog_txtColNum = null;
		public String CollBoeDialog_txtColDesc = null;
		public BigDecimal CollBoeDialog_COL_TYPE_ID = null;
		public String CollBoeDialog_txtCollTypeCode = null;
		public String CollBoeDialog_txtCollTypeName = null;
		public BigDecimal CollBoeDialog_CUS_ID = null;
		public String CollBoeDialog_txtRegNoB = null;
		public String CollBoeDialog_txtCodeB = null;
		public String CollBoeDialog_txtNameB = null;
		public BigDecimal CollBoeDialog_BOE_TYPE_ID = null;
		public String CollBoeDialog_txtBoeTypeUCV = null;
		public String CollBoeDialog_txtBoeTypeUCD = null;
		public BigDecimal CollBoeDialog_ISU_PLACE_ID = null;
		public String CollBoeDialog_txtIsuPlaCode = null;
		public String CollBoeDialog_txtIssuePlace = null;
		public Date CollBoeDialog_txtIssueDate = null;
		public BigDecimal CollBoeDialog_txtAmount = null;
		public BigDecimal CollBoeDialog_CUR_ID = null;
		public String CollBoeDialog_txtCurIdCodeChar = null;
		public BigDecimal CollBoeDialog_P_CUS_ID = null;
		public String CollBoeDialog_txtRegNoP = null;
		public String CollBoeDialog_txtCodeP = null;
		public String CollBoeDialog_txtNamePayee = null;
		public String CollBoeDialog_txtPayeeAccno = null;
		public String CollBoeDialog_txtAddData = null;
		public String CollBoeDialog_txtAddData1 = null;
		public BigDecimal CollBoeDialog_TR_CUS_ID = null;
		public String CollBoeDialog_txtRegNoTR = null;
		public String CollBoeDialog_txtCodeTR = null;
		public String CollBoeDialog_txtNameTR = null;
		public String CollBoeDialog_txtFNameTR = null;
		public String CollBoeDialog_txtSNameTR = null;
		public BigDecimal CollBoeDialog_PAY_PLACE_ID = null;
		public String CollBoeDialog_txtPayPlaceCode = null;
		public String CollBoeDialog_txtPayPlace = null;
		public String CollBoeDialog_txtPayment = null;
		public BigDecimal CollBoeDialog_COLL_CUS_ID = null;
		public String CollBoeDialog_txtRegNoT = null;
		public String CollBoeDialog_txtCodeT = null;
		public String CollBoeDialog_txtNameT = null;
		public String CollBoeDialog_txtFName = null;
		public String CollBoeDialog_txtSName = null;
		public String CollBoeDialog_txtNumberClause = null;
		public Integer CollBoeDialog_txtNumberBoe = null;
		public String CollBoeDialog_txtMaturityClause = null;
		public Date CollBoeDialog_txtMaturityDate = null;
		public String CollBoeDialog_txtPaymentClause = null;
		public String CollBoeDialog_txtProtestClause = null;
		public String CollBoeDialog_txtFeeClause = null;
		public String CollBoeDialog_txtReportClause = null;
		public String CollBoeDialog_txtIndosaClause = null;
		public String CollBoeDialog_txtCureClause = null;
		public Date CollBoeDialog_txtDATE_FROM = null;
		public Date CollBoeDialog_txtDATE_UNTIL = null;
		public String CollBoeDialog_Status = null;
		public String CollBoeDialog_StatusDesc = null;
		public String CollBoeDialog_SpecStatus = null;
		public String CollBoeDialog_SpecStatusDesc = null;
		public BigDecimal CollBoeDialog_USE_OPEN_ID = null;
		public BigDecimal CollBoeDialog_USE_ID = null;
		public BigDecimal CollBoeDialog_LA_ACC_ID = null;
		public String CollBoeDialog_txtAccNoLoan = null;
		public BigDecimal CollBoeDialog_PAYEE_ADD_ID = null;
		public String CollBoeDialog_txtPayeeFname = null;
		public String CollBoeDialog_txtPayeeSname = null;
		public BigDecimal RealEstate_ORIGIN_ORG_UNI_ID = null;
		public BigDecimal CollBoeDialog_ORG_UNI_ID = null;
		public BigDecimal CollBoeDialog_USE_ID_VER_SND = null;
		public Timestamp CollBoeDialog_VER_SEND_TS = null;
		public BigDecimal CollBoeDialog_USE_ID_VER = null;
		public Timestamp CollBoeDialog_VERIFICATION_TS = null;
		public BigDecimal CollBoeDialog_USE_ID_AUT = null;
		public Timestamp CollBoeDialog_AUTORIZATION_TS = null;
		public String CollBoeDialog_BasicDataStatus = null;
		public String CollBoeDialog_MortgageStatus = null;
		public String CollBoeDialog_CoverIndic = null;
		public String CollBoeDialog_CollDataStatus = null;
		public String CollBoeDialog_FinancialFlag = null;
		public String CollBoeDialog_CollateralStatus = null;
		public String CollBoeDialog_WorkflowIndic = null;
		public BigDecimal CollBoeDialog_COL_CAT_ID = null;
		public String save_ver_aut_flag = null;
		public BigDecimal CollBoeDialog_BOE_ID = null;
		public String CollBoeDialog_txtSerLet = null;
		public String CollBoeDialog_txtSerNo = null;
		public Timestamp CollBoeDialog_USER_LOCK_IN = null;
		public BigDecimal CollBoeDialog_CUS_IDInd1 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd2 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd3 = null;
		public BigDecimal CollBoeDialog_CUS_IDInd4 = null;
		public String CollBoeDialog_txtRegNoInd1 = null;
		public String CollBoeDialog_txtRegNoInd2 = null;
		public String CollBoeDialog_txtRegNoInd3 = null;
		public String CollBoeDialog_txtRegNoInd4 = null;
		public String ColBoeLow_txtEligibility = null;
		public String ColBoeRba_txtEligibility = null;
		public String Kol_txtAval = null;
		public BigDecimal cus_id_aval1 = null;
		public String KolBD_txtRegNoAval1 = null;
		public BigDecimal cus_id_aval2 = null;
		public String KolBD_txtRegNoAval2 = null;
		public BigDecimal cus_id_aval3 = null;
		public String KolBD_txtRegNoAval3 = null;
		public BigDecimal cus_id_aval4 = null;
		public String KolBD_txtRegNoAval4 = null;
		public String Kol_txtRbaEligDsc1 = null;
		public BigDecimal CUS_ID = null;
		public Integer Coll_txtNumOf = null;
		public String Kol_txtCRMHnbBoe = null;
		public String Coll_txtB2HNB = null;
		public String Coll_txtB2IRB = null;
		public String Coll_txtContractTypeCode = null;

		// out args
		public Timestamp CollBoeDialog_USER_LOCK = null;
		public String Coll_txtB1Eligibility1 = null;
		public String Coll_txtB1EligDesc1 = null;
		public String Coll_txtB2IRBEligibility1 = null;
		public String Coll_txtB2IRBEligDesc1 = null;
		public String Coll_txtNDEligibility = null;
		public String Coll_txtNDEligDesc = null;
		public String CollBoeDialog_txtEligibility = null;
		public String CollBoeDialog_txtEligDesc = null;
		public Timestamp CollBoeDialog_txtUserLock = null;
		public BigDecimal Coll_txtRealPonderAmount = null;
		public String Coll_txtWcaOrigCurrencyCode = null;
		public BigDecimal Coll_txtUsedWCAAmount = null;
		public String Coll_txtCollateralGCTCCode = null;
		public String Coll_txtCollateralGCTCDesc = null;
		public String Coll_txtEndorsementTypeGCTCCode = null;
		public String Coll_txtEndorsementTypeGCTCDesc = null;
		public String Coll_txtObjectTypeGCTCCode = null;
		public String Coll_txtObjectTypeGCTCDesc = null;
		public String Coll_txtPropertyTypeGCTCCode = null;
		public String Coll_txtPropertyTypeGCTCDesc = null;
		public BigDecimal Coll_txtB2ValueLLAmount = null;
		public String Coll_txtB2ValueLLCurCode = null;
		public BigDecimal Coll_txtB2ValueGLAmount = null;
		public String Coll_txtB2ValueGLCurCode = null;
		public BigDecimal Coll_txtSumHipToFirstRBA = null;

		public COLLBOEUPDATEMAPPING(Map request) {
			setRequest(request);
		}

		public void setRequest(Map request) {
			CollBoeDialog_COL_HEA_ID = (BigDecimal) request.get("CollBoeDialog_COL_HEA_ID");
			CollBoeDialog_txtColNum = (String) request.get("CollBoeDialog_txtColNum");
			CollBoeDialog_txtColDesc = (String) request.get("CollBoeDialog_txtColDesc");
			CollBoeDialog_COL_TYPE_ID = (BigDecimal) request.get("CollBoeDialog_COL_TYPE_ID");
			CollBoeDialog_txtCollTypeCode = (String) request.get("CollBoeDialog_txtCollTypeCode");
			CollBoeDialog_txtCollTypeName = (String) request.get("CollBoeDialog_txtCollTypeName");
			CollBoeDialog_CUS_ID = (BigDecimal) request.get("CollBoeDialog_CUS_ID");
			CollBoeDialog_txtRegNoB = (String) request.get("CollBoeDialog_txtRegNoB");
			CollBoeDialog_txtCodeB = (String) request.get("CollBoeDialog_txtCodeB");
			CollBoeDialog_txtNameB = (String) request.get("CollBoeDialog_txtNameB");
			CollBoeDialog_BOE_TYPE_ID = (BigDecimal) request.get("CollBoeDialog_BOE_TYPE_ID");
			CollBoeDialog_txtBoeTypeUCV = (String) request.get("CollBoeDialog_txtBoeTypeUCV");
			CollBoeDialog_txtBoeTypeUCD = (String) request.get("CollBoeDialog_txtBoeTypeUCD");
			CollBoeDialog_ISU_PLACE_ID = (BigDecimal) request.get("CollBoeDialog_ISU_PLACE_ID");
			CollBoeDialog_txtIsuPlaCode = (String) request.get("CollBoeDialog_txtIsuPlaCode");
			CollBoeDialog_txtIssuePlace = (String) request.get("CollBoeDialog_txtIssuePlace");
			CollBoeDialog_txtIssueDate = (Date) request.get("CollBoeDialog_txtIssueDate");
			CollBoeDialog_txtAmount = (BigDecimal) request.get("CollBoeDialog_txtAmount");
			CollBoeDialog_CUR_ID = (BigDecimal) request.get("CollBoeDialog_CUR_ID");
			CollBoeDialog_txtCurIdCodeChar = (String) request.get("CollBoeDialog_txtCurIdCodeChar");
			CollBoeDialog_P_CUS_ID = (BigDecimal) request.get("CollBoeDialog_P_CUS_ID");
			CollBoeDialog_txtRegNoP = (String) request.get("CollBoeDialog_txtRegNoP");
			CollBoeDialog_txtCodeP = (String) request.get("CollBoeDialog_txtCodeP");
			CollBoeDialog_txtNamePayee = (String) request.get("CollBoeDialog_txtNamePayee");
			CollBoeDialog_txtPayeeAccno = (String) request.get("CollBoeDialog_txtPayeeAccno");
			CollBoeDialog_txtAddData = (String) request.get("CollBoeDialog_txtAddData");
			CollBoeDialog_txtAddData1 = (String) request.get("CollBoeDialog_txtAddData1");
			CollBoeDialog_TR_CUS_ID = (BigDecimal) request.get("CollBoeDialog_TR_CUS_ID");
			CollBoeDialog_txtRegNoTR = (String) request.get("CollBoeDialog_txtRegNoTR");
			CollBoeDialog_txtCodeTR = (String) request.get("CollBoeDialog_txtCodeTR");
			CollBoeDialog_txtNameTR = (String) request.get("CollBoeDialog_txtNameTR");
			CollBoeDialog_txtFNameTR = (String) request.get("CollBoeDialog_txtFNameTR");
			CollBoeDialog_txtSNameTR = (String) request.get("CollBoeDialog_txtSNameTR");
			CollBoeDialog_PAY_PLACE_ID = (BigDecimal) request.get("CollBoeDialog_PAY_PLACE_ID");
			CollBoeDialog_txtPayPlaceCode = (String) request.get("CollBoeDialog_txtPayPlaceCode");
			CollBoeDialog_txtPayPlace = (String) request.get("CollBoeDialog_txtPayPlace");
			CollBoeDialog_txtPayment = (String) request.get("CollBoeDialog_txtPayment");
			CollBoeDialog_COLL_CUS_ID = (BigDecimal) request.get("CollBoeDialog_COLL_CUS_ID");
			CollBoeDialog_txtRegNoT = (String) request.get("CollBoeDialog_txtRegNoT");
			CollBoeDialog_txtCodeT = (String) request.get("CollBoeDialog_txtCodeT");
			CollBoeDialog_txtNameT = (String) request.get("CollBoeDialog_txtNameT");
			CollBoeDialog_txtFName = (String) request.get("CollBoeDialog_txtFName");
			CollBoeDialog_txtSName = (String) request.get("CollBoeDialog_txtSName");
			CollBoeDialog_txtNumberClause = (String) request.get("CollBoeDialog_txtNumberClause");
			CollBoeDialog_txtNumberBoe = (Integer) request.get("CollBoeDialog_txtNumberBoe");
			CollBoeDialog_txtMaturityClause = (String) request.get("CollBoeDialog_txtMaturityClause");
			CollBoeDialog_txtMaturityDate = (Date) request.get("CollBoeDialog_txtMaturityDate");
			CollBoeDialog_txtPaymentClause = (String) request.get("CollBoeDialog_txtPaymentClause");
			CollBoeDialog_txtProtestClause = (String) request.get("CollBoeDialog_txtProtestClause");
			CollBoeDialog_txtFeeClause = (String) request.get("CollBoeDialog_txtFeeClause");
			CollBoeDialog_txtReportClause = (String) request.get("CollBoeDialog_txtReportClause");
			CollBoeDialog_txtIndosaClause = (String) request.get("CollBoeDialog_txtIndosaClause");
			CollBoeDialog_txtCureClause = (String) request.get("CollBoeDialog_txtCureClause");
			CollBoeDialog_txtDATE_FROM = (Date) request.get("CollBoeDialog_txtDATE_FROM");
			CollBoeDialog_txtDATE_UNTIL = (Date) request.get("CollBoeDialog_txtDATE_UNTIL");
			CollBoeDialog_Status = (String) request.get("CollBoeDialog_Status");
			CollBoeDialog_StatusDesc = (String) request.get("CollBoeDialog_StatusDesc");
			CollBoeDialog_SpecStatus = (String) request.get("CollBoeDialog_SpecStatus");
			CollBoeDialog_SpecStatusDesc = (String) request.get("CollBoeDialog_SpecStatusDesc");
			CollBoeDialog_USE_OPEN_ID = (BigDecimal) request.get("CollBoeDialog_USE_OPEN_ID");
			CollBoeDialog_USE_ID = (BigDecimal) request.get("CollBoeDialog_USE_ID");
			CollBoeDialog_LA_ACC_ID = (BigDecimal) request.get("CollBoeDialog_LA_ACC_ID");
			CollBoeDialog_txtAccNoLoan = (String) request.get("CollBoeDialog_txtAccNoLoan");
			CollBoeDialog_PAYEE_ADD_ID = (BigDecimal) request.get("CollBoeDialog_PAYEE_ADD_ID");
			CollBoeDialog_txtPayeeFname = (String) request.get("CollBoeDialog_txtPayeeFname");
			CollBoeDialog_txtPayeeSname = (String) request.get("CollBoeDialog_txtPayeeSname");
			RealEstate_ORIGIN_ORG_UNI_ID = (BigDecimal) request.get("RealEstate_ORIGIN_ORG_UNI_ID");
			CollBoeDialog_ORG_UNI_ID = (BigDecimal) request.get("CollBoeDialog_ORG_UNI_ID");
			CollBoeDialog_USE_ID_VER_SND = (BigDecimal) request.get("CollBoeDialog_USE_ID_VER_SND");
			CollBoeDialog_VER_SEND_TS = (Timestamp) request.get("CollBoeDialog_VER_SEND_TS");
			CollBoeDialog_USE_ID_VER = (BigDecimal) request.get("CollBoeDialog_USE_ID_VER");
			CollBoeDialog_VERIFICATION_TS = (Timestamp) request.get("CollBoeDialog_VERIFICATION_TS");
			CollBoeDialog_USE_ID_AUT = (BigDecimal) request.get("CollBoeDialog_USE_ID_AUT");
			CollBoeDialog_AUTORIZATION_TS = (Timestamp) request.get("CollBoeDialog_AUTORIZATION_TS");
			CollBoeDialog_BasicDataStatus = (String) request.get("CollBoeDialog_BasicDataStatus");
			CollBoeDialog_MortgageStatus = (String) request.get("CollBoeDialog_MortgageStatus");
			CollBoeDialog_CoverIndic = (String) request.get("CollBoeDialog_CoverIndic");
			CollBoeDialog_CollDataStatus = (String) request.get("CollBoeDialog_CollDataStatus");
			CollBoeDialog_FinancialFlag = (String) request.get("CollBoeDialog_FinancialFlag");
			CollBoeDialog_CollateralStatus = (String) request.get("CollBoeDialog_CollateralStatus");
			CollBoeDialog_WorkflowIndic = (String) request.get("CollBoeDialog_WorkflowIndic");
			CollBoeDialog_COL_CAT_ID = (BigDecimal) request.get("CollBoeDialog_COL_CAT_ID");
			save_ver_aut_flag = (String) request.get("save_ver_aut_flag");
			CollBoeDialog_BOE_ID = (BigDecimal) request.get("CollBoeDialog_BOE_ID");
			CollBoeDialog_txtSerLet = (String) request.get("CollBoeDialog_txtSerLet");
			CollBoeDialog_txtSerNo = (String) request.get("CollBoeDialog_txtSerNo");
			CollBoeDialog_USER_LOCK_IN = (Timestamp) request.get("CollBoeDialog_USER_LOCK_IN");
			CollBoeDialog_CUS_IDInd1 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd1");
			CollBoeDialog_CUS_IDInd2 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd2");
			CollBoeDialog_CUS_IDInd3 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd3");
			CollBoeDialog_CUS_IDInd4 = (BigDecimal) request.get("CollBoeDialog_CUS_IDInd4");
			CollBoeDialog_txtRegNoInd1 = (String) request.get("CollBoeDialog_txtRegNoInd1");
			CollBoeDialog_txtRegNoInd2 = (String) request.get("CollBoeDialog_txtRegNoInd2");
			CollBoeDialog_txtRegNoInd3 = (String) request.get("CollBoeDialog_txtRegNoInd3");
			CollBoeDialog_txtRegNoInd4 = (String) request.get("CollBoeDialog_txtRegNoInd4");
			ColBoeLow_txtEligibility = (String) request.get("ColBoeLow_txtEligibility");
			ColBoeRba_txtEligibility = (String) request.get("ColBoeRba_txtEligibility");
			Kol_txtAval = (String) request.get("Kol_txtAval");
			cus_id_aval1 = (BigDecimal) request.get("cus_id_aval1");
			KolBD_txtRegNoAval1 = (String) request.get("KolBD_txtRegNoAval1");
			cus_id_aval2 = (BigDecimal) request.get("cus_id_aval2");
			KolBD_txtRegNoAval2 = (String) request.get("KolBD_txtRegNoAval2");
			cus_id_aval3 = (BigDecimal) request.get("cus_id_aval3");
			KolBD_txtRegNoAval3 = (String) request.get("KolBD_txtRegNoAval3");
			cus_id_aval4 = (BigDecimal) request.get("cus_id_aval4");
			KolBD_txtRegNoAval4 = (String) request.get("KolBD_txtRegNoAval4");
			Kol_txtRbaEligDsc1 = (String) request.get("Kol_txtRbaEligDsc1");
			CUS_ID = (BigDecimal) request.get("CUS_ID");
			Coll_txtNumOf = (Integer) request.get("Coll_txtNumOf");
			Kol_txtCRMHnbBoe = (String) request.get("Kol_txtCRMHnbBoe");
			Coll_txtB2HNB = (String) request.get("Coll_txtB2HNB");
			Coll_txtB2IRB = (String) request.get("Coll_txtB2IRB");
			Coll_txtContractTypeCode = (String) request.get("Coll_txtContractTypeCode");
		}

		public Map getResponse() {
			response.put("CollBoeDialog_USER_LOCK", CollBoeDialog_USER_LOCK);
			response.put("Coll_txtB1Eligibility1", Coll_txtB1Eligibility1);
			response.put("Coll_txtB1EligDesc1", Coll_txtB1EligDesc1);
			response.put("Coll_txtB2IRBEligibility1", Coll_txtB2IRBEligibility1);
			response.put("Coll_txtB2IRBEligDesc1", Coll_txtB2IRBEligDesc1);
			response.put("Coll_txtNDEligibility", Coll_txtNDEligibility);
			response.put("Coll_txtNDEligDesc", Coll_txtNDEligDesc);
			response.put("CollBoeDialog_txtEligibility", CollBoeDialog_txtEligibility);
			response.put("CollBoeDialog_txtEligDesc", CollBoeDialog_txtEligDesc);
			response.put("CollBoeDialog_txtUserLock", CollBoeDialog_txtUserLock);
			response.put("Coll_txtRealPonderAmount", Coll_txtRealPonderAmount);
			response.put("Coll_txtWcaOrigCurrencyCode", Coll_txtWcaOrigCurrencyCode);
			response.put("Coll_txtUsedWCAAmount", Coll_txtUsedWCAAmount);
			response.put("Coll_txtCollateralGCTCCode", Coll_txtCollateralGCTCCode);
			response.put("Coll_txtCollateralGCTCDesc", Coll_txtCollateralGCTCDesc);
			response.put("Coll_txtEndorsementTypeGCTCCode", Coll_txtEndorsementTypeGCTCCode);
			response.put("Coll_txtEndorsementTypeGCTCDesc", Coll_txtEndorsementTypeGCTCDesc);
			response.put("Coll_txtObjectTypeGCTCCode", Coll_txtObjectTypeGCTCCode);
			response.put("Coll_txtObjectTypeGCTCDesc", Coll_txtObjectTypeGCTCDesc);
			response.put("Coll_txtPropertyTypeGCTCCode", Coll_txtPropertyTypeGCTCCode);
			response.put("Coll_txtPropertyTypeGCTCDesc", Coll_txtPropertyTypeGCTCDesc);
			response.put("Coll_txtB2ValueLLAmount", Coll_txtB2ValueLLAmount);
			response.put("Coll_txtB2ValueLLCurCode", Coll_txtB2ValueLLCurCode);
			response.put("Coll_txtB2ValueGLAmount", Coll_txtB2ValueGLAmount);
			response.put("Coll_txtB2ValueGLCurCode", Coll_txtB2ValueGLCurCode);
			response.put("Coll_txtSumHipToFirstRBA", Coll_txtSumHipToFirstRBA);

			return response;
		}

		public Map getRefToResponseMap() {
			return response;
		}

	}

	public class COLLBOEQBEMAPP implements MappingDecl {
		public Map response = new HashMap();

		// in args
		public java.lang.Integer ActionListLevel = null;
		public String ScreenEntryParam = null;
		public BigDecimal use_id = null;
		public BigDecimal org_uni_id = null;
		public String RealEstate_txtOwnerQbeRegNo2 = null;
		public String RealEstate_txtCarrierQbeRegNo2 = null;
		public String RealEstate_txtQbeAccNo2 = null;
		public String RealEstate_txtQbeCode2 = null;
		public BigDecimal RealEstate_Qbe_ORG_UNI_ID2 = null;
		public BigDecimal RealEstate_QbeUSE_OPEN_ID2 = null;
		public Date RealEstate_txtQbeDateFrom2 = null;
		public Date RealEstate_txtQbeDateUntil2 = null;
		public String RealEstate_txtQbeRequestNo2 = null;

		// out args
		public TableData tblColWorkList = new TableData();

		public COLLBOEQBEMAPP(Map request) {
			setRequest(request);
		}

		public void setRequest(Map request) {
			ActionListLevel = (java.lang.Integer) request.get("ActionListLevel");
			ScreenEntryParam = (String) request.get("ScreenEntryParam");
			use_id = (BigDecimal) request.get("use_id");
			org_uni_id = (BigDecimal) request.get("org_uni_id");
			RealEstate_txtOwnerQbeRegNo2 = (String) request.get("RealEstate_txtOwnerQbeRegNo2");
			RealEstate_txtCarrierQbeRegNo2 = (String) request.get("RealEstate_txtCarrierQbeRegNo2");
			RealEstate_txtQbeAccNo2 = (String) request.get("RealEstate_txtQbeAccNo2");
			RealEstate_txtQbeCode2 = (String) request.get("RealEstate_txtQbeCode2");
			RealEstate_Qbe_ORG_UNI_ID2 = (BigDecimal) request.get("RealEstate_Qbe_ORG_UNI_ID2");
			RealEstate_QbeUSE_OPEN_ID2 = (BigDecimal) request.get("RealEstate_QbeUSE_OPEN_ID2");
			RealEstate_txtQbeDateFrom2 = (Date) request.get("RealEstate_txtQbeDateFrom2");
			RealEstate_txtQbeDateUntil2 = (Date) request.get("RealEstate_txtQbeDateUntil2");
			RealEstate_txtQbeRequestNo2 = (String) request.get("RealEstate_txtQbeRequestNo2");
		}

		public Map getResponse() {
			response.put("tblColWorkList", tblColWorkList);

			return response;
		}

		public Map getRefToResponseMap() {
			return response;
		}

	}

}